# Generated by Django 4.2.5 on 2023-09-11 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0002_license_licenseappmap_offer_offerappmap_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerappmap',
            name='active_license_count',
        ),
    ]
