# Generated by Django 4.2.5 on 2023-09-11 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0003_remove_offerappmap_active_license_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferUserMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flux.offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flux.user')),
            ],
        ),
    ]
